image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  PLAN: plan.tfplan
  TF_IN_AUTOMATION: "true"

.variables_prod: &variables_prod
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_prod
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_prod
    TF_VAR_aws_allowed_accounts: $AWS_ALLOWED_ACCOUNTS_prod
    TF_VAR_aws_assume_role: $AWS_ASSUME_ROLE_prod
    TF_STATE_BUCKET: $TF_STATE_BUCKET_prod
    TF_VAR_domain: mediacodex.net

.variables_dev: &variables_dev
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_dev
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_dev
    TF_VAR_aws_allowed_accounts: $AWS_ALLOWED_ACCOUNTS_dev
    TF_VAR_aws_assume_role: $AWS_ASSUME_ROLE_dev
    TF_STATE_BUCKET: $TF_STATE_BUCKET_dev
    TF_VAR_domain: mediacodex.dev

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .terraform

stages:
  - validate
  - plan
  - apply

sonarcloud:
  stage: .pre
  allow_failure: true
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
    - develop

validate:
  stage: validate
  before_script:
    - terraform init -backend=false terraform/
  script:
    - terraform validate terraform/
    - terraform fmt -check=true terraform/
  only:
    - branches

.script_review: &script_review
  script:
    - apk add curl
    - terraform plan -out=$PLAN terraform/
    - echo \`\`\`diff > plan.txt
    - (cd terraform && cp -r ../.terraform/ .terraform/  && terraform show -no-color ../${PLAN}) | tee -a ../plan.txt
    - echo \`\`\` >> plan.txt
    - sed -i -e 's/  +/+/g' plan.txt
    - sed -i -e 's/  ~/~/g' plan.txt
    - sed -i -e 's/  -/-/g' plan.txt
    - MESSAGE=$(cat plan.txt)
    - >-
      curl -X POST -g -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}"
      --data-urlencode "body=${MESSAGE}"
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}/discussions"

plan_dev:
  <<: *variables_dev
  <<: *script_review
  stage: plan
  before_script:
    - terraform init -backend-config="bucket=${TF_STATE_BUCKET}" terraform/
  artifacts:
    name: plan
    paths:
      - $PLAN
  only:
    - merge_requests

plan_prod:
  <<: *variables_prod
  <<: *script_review
  stage: plan
  before_script:
    - terraform init -backend-config="bucket=${TF_STATE_BUCKET}" terraform/
  artifacts:
    name: plan
    paths:
      - $PLAN
  only:
    - merge_requests

deploy_dev:
  <<: *variables_dev
  stage: apply
  before_script:
    - terraform --version
    - terraform init terraform/
  script:
    terraform apply -plan=$PLAN terraform/
  environment:
    name: development
  when: manual
  dependencies:
    - plan_dev
  only:
    - develop

deploy_prod:
  <<: *variables_prod
  before_script:
    - terraform --version
    - terraform init terraform/
  stage: apply
  script:
    terraform apply -plan=$PLAN terraform/
  environment:
    name: production
  when: manual
  dependencies:
    - plan_prod
  only:
    - master
