image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  PLAN: plan.tfplan
  TF_IN_AUTOMATION: "true"

.variables_prod: &variables_prod
  variables:
    AWS_ACCESS_KEY_ID: $env:AWS_ACCESS_KEY_ID_prod
    AWS_SECRET_ACCESS_KEY: $env:AWS_SECRET_ACCESS_KEY_prod
    TF_VAR_aws_allowed_accounts: $env:AWS_ALLOWED_ACCOUNTS_prod

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .terraform

stages:
  - initialise
  - validate
  - plan
  - apply

sonarcloud:
  stage: .pre
  allow_failure: true
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
    - develop

initialise:
  stage: initialise
  script:
    - terraform --version
    - terraform init

validate:
  stage: validate
  script:
    - terraform validate terraform/
    - terraform fmt -check=true terraform/
  only:
    - branches

deploy_prod:
  <<: *variables_prod
  stage: apply
  script:
    terraform apply -plan=$PLAN terraform/
  environment:
    name: production
  when: manual
  only:
  - master

merge_review_prod:
  <<: *variables_prod
  stage: plan
  script:
    - terraform plan -out=$PLAN terraform/
    - echo \`\`\`diff > plan.txt
    - terraform show -no-color ${PLAN} | tee -a plan.txt
    - echo \`\`\` >> plan.txt
    - sed -i -e 's/  +/+/g' plan.txt
    - sed -i -e 's/  ~/~/g' plan.txt
    - sed -i -e 's/  -/-/g' plan.txt
    - MESSAGE=$(cat plan.txt)
    - >-
      curl -X POST -g -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}"
      --data-urlencode "body=${MESSAGE}"
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}/discussions"
  artifacts:
    name: plan
    paths:
      - $PLAN
  only:
    - merge_requests
    - master
