default:
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .terraform

variables:
  TF_PLAN: plan.tfplan
  TF_PATH: terraform/
  TF_IN_AUTOMATION: "true"
  PROD_ONLY: 'false'

stages:
  - validate
  - plan
  - deploy

.terraform-image:
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

.variables_prod: &variables_prod
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_prod
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_prod

.variables_dev: &variables_dev
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_dev
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_dev

###
# Shared
###
.plan_review:
  script:
    - apk add curl
    - terraform init $TF_PATH
    - terraform workspace select $CI_ENVIRONMENT_NAME $TF_PATH
    - terraform plan -out=$TF_PLAN $TF_PATH
    - echo "# Terraform planned changes ($(terraform workspace show $TF_PATH))\n" > plan.txt
    - echo \`\`\`diff > plan.txt
    - (cd terraform && cp -r ../.terraform/ .terraform/  && terraform show -no-color ../${PLAN}) | tee -a ../plan.txt
    - echo \`\`\` >> plan.txt
    - sed -i -e 's/  +/+/g' plan.txt
    - sed -i -e 's/  ~/~/g' plan.txt
    - sed -i -e 's/  -/-/g' plan.txt
    - MESSAGE=$(cat plan.txt)
    - >-
      curl -X POST -g -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}"
      --data-urlencode "body=${MESSAGE}"
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}/discussions"

.plan:
  stage: plan
  script:
    - terraform init $TF_PATH
    - terraform workspace select $CI_ENVIRONMENT_NAME $TF_PATH
    - terrrform plan -out=$TF_PLAN $TF_PATH
  artifacts:
    name: plan
    paths:
      - $TF_PLAN
  only:
    - merge_requests

.deploy:
  stage: deploy
  script:
    - terraform init $TF_PATH
    - terraform workspace select $CI_ENVIRONMENT_NAME $TF_PATH
    - terraform apply -plan=$TF_PLAN $TF_PATH

###
# pre-deploy
###
validate_terraform:
  extends:
    - .terraform-image
  stage: validate
  script:
    - terraform --version
    - terraform init -backend=false $TF_PATH
    - terraform validate $TF_PATH
    - terraform fmt -check=true -recursive=true $TF_PATH

###
# Dev
###
plan_dev:
  <<: *variables_dev
  extends:
    - .plan
    - .plan_review
    - .terraform-image
  environment:
    name: development
  except:
    variables:
      - $PROD_ONLY == 'true'

apply_dev:
  <<: *variables_dev
  extends:
    - .deploy
    - .terraform-image
  environment:
    name: development
  dependencies:
    - plan_dev
  only:
    - master
  except:
    variables:
      - $PROD_ONLY == 'true'

###
# Prod
###
plan_prod:
  <<: *variables_prod
  extends:
    - .plan
    - .plan_review
    - .terraform-image
  environment:
    name: production

apply_prod:
  <<: *variables_prod
  extends: 
    - .deploy
    - .terraform-image
  environment:
    name: production
  dependencies:
    - plan_prod
  only:
    - master
  when: manual